-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = true,
            special = false,
            size = 5,
            passes = 2,
        },
        dim_inactive = false,
        rounding = 15,
    },
    general = {
        layout = "dwindle",
    },
})

-- Bezier curves
hl.curve("standard", { type = "bezier", points = { {0.2, 0.0}, {0.0, 1.0} } })

-- Animations
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 6.0,
    bezier = "standard",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 6.0,
    bezier = "standard",
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1366x768@60.00Hz",
    position = "0x0",
    scale = 0.67,
    cm = "srgb",
})
