-- Vanish Mode Dedicated Keybindings
-- Auto-generated by Carbon Config Editor (Vanish Shortcuts tab)
-- Decoupled from standard keybinds.lua and variables.lua

local fn = require("hyprland.functions")

-- Vanish App Launcher (SUPER + ALT)
hl.bind("SUPER + Alt_L", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh launcher"))
hl.bind("SUPER + Alt_R", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh launcher"))
hl.bind("ALT + Super_L", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh launcher"))
hl.bind("ALT + Super_R", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh launcher"))

hl.bind("SUPER + Alt_L", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh launcher"), { release = true })
hl.bind("SUPER + Alt_R", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh launcher"), { release = true })
hl.bind("ALT + Super_L", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh launcher"), { release = true })
hl.bind("ALT + Super_R", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh launcher"), { release = true })

-- Vanish Synced Lyrics (SUPER + M)
hl.bind("SUPER + M", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh lyrics"))

-- Vanish Wallpaper Ring (SUPER + W)
hl.bind("SUPER + W", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh wallpaper"))

-- Vanish Direct Lobe Blooms
hl.bind("SUPER + C", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh focus-connect"))
hl.bind("SUPER + S", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh focus-spaces"))
hl.bind("SUPER + N", hl.dsp.exec_cmd("sh ~/.config/hypr/scripts/carbon-vanish-dispatch.sh focus-alerts"))
