windowrule = tag +multimedia_video, match:class mpv|vlc
windowrule = tag +settings, match:class nm-applet|nm-connection-editor|blueman-manager|org.gnome.FileRoller
windowrule = tag +settings, match:class org.gnome.DiskUtility|wihotspot
windowrule = tag +viewer, match:class org.gnome.SystemMonitor
windowrule = tag +viewer, match:class org.gnome.Evince
windowrule = tag +viewer, match:class eog|org.gnome.Loupe
