windowrule = opacity 1.0, match:tag multimedia_video
windowrule = opacity 0.8, match:tag settings
windowrule = opacity 0.8, match:class org.gnome.Nautilus
windowrule = opacity 0.9, match:class gedit|org.gnome.TextEditor|mousepad
windowrule = opacity 0.9, match:class org.pulseaudio.pavucontrol
windowrule = opacity 0.9, match:class kitty
windowrule = opacity 0.85 override 0.7 override 1 override, match:class discord|vesktop|org.telegram.desktop
windowrule = opacity 0.8 override 0.6 override 1 override, match:class Spotify
windowrule = opacity 0.9 override 0.7 override 1 override, match:class zen

layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.5, match:namespace waybar
layerrule = blur on, match:namespace carbon
layerrule = ignore_alpha 0.5, match:namespace carbon
layerrule = blur on, match:namespace carbon-overview
layerrule = ignore_alpha 0.1, match:namespace carbon-overview
layerrule = ignore_alpha 0.5, match:namespace notifications
layerrule = blur on, match:namespace logout_dialog

layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window

windowrule = float on, match:tag settings
windowrule = float on, match:tag viewer
windowrule = float on, match:tag multimedia_video
windowrule = size 900 506, match:tag multimedia_video
windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = size 50% 60%, match:class org.pulseaudio.pavucontrol
windowrule = float on, match:class org.carbon.configeditor
windowrule = size 60% 70%, match:class org.carbon.configeditor
windowrule = center on, match:class org.carbon.configeditor

windowrule = float on, match:title Save As|Save a File|Pick Files
windowrule = size 50% 60%, match:title Save As|Save a File|Pick Files
windowrule = center on, match:title Save As|Save a File|Pick Files

windowrule = float on, match:initial_title Open Files
windowrule = size 70% 60%, match:initial_title Open Files

# Discord: if floated manually, fit comfortably within work area
windowrule = size 1200 660, match:class discord
windowrule = center, match:class discord
